name: CI

on:
  push:
    branches:
      - "master"
      - "staging"
      - "trying"
  pull_request:

env:
  NODE_JS: "24"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_JS }}
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn check:spell
      - run: yarn build
